### ISSUE TITLE
[FE] 여행지 검색 뷰 생성

### ISSUE THREAD

**Issue by 17wook2** [goalduo/cheil-trip-front#10]

**Comment by 17wook2** [comment]
[ ] : 공공 데이터 API와 연동해 기존 jsp 파일을 vue로 연결
[ ] : 카카오맵 생성

**Comment by jangsumin** [comment]
- [ ] 여행지 검색 뷰 마크업

**Comment by jangsumin** [comment]
- [ ] 여행지 검색 뷰 스타일링
- [ ] 검색 기능 확인하고, 적용하기
- [ ] 카카오 맵 출력 잘 되는지 확인하기
- [ ] 검색된 내용들을 하위 컴포넌트로 만들기
- [ ] 검색된 내용의 하위 컴포넌트에 경로에 추가하기 버튼 만들기
- [ ] 경로에 추가하기 버튼을 누르면 경로 요소에 추가하기
- [ ] 경로 요소에 들어갈 컴포넌트 생성
